# .air.toml

# Working directory
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/grocery-app ./cmd/api"
  bin = "tmp/grocery-app"
  full_bin = "./tmp/grocery-app"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules"]
  include_dir = []
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = true
  log = "air.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true